### ISSUE TITLE
Start this week by adding the new JS validation footer I shared to your web pages.

### ISSUE THREAD

**Issue by jelkner** [jydenn/website#10]
Your CSS validation links aren't working (see your [homepage](https://jydenn.github.io/website/), for example).  Please use the new JavaScript validation link footer I shared with you in class in the [min.html](https://ict.gctaa.net/sections/webdesign/resources/min.html). It will make your life (and mine ;-) easier.

**Comment by jydenn** [comment]
It took a while but I fixed all of the links
