### ISSUE TITLE
Please remove unneeded page and add "What's New" section

### ISSUE THREAD

**Issue by jelkner** [jydenn/website#11]
You have [a page](https://jydenn.github.io/website/XMASProject/index.html) between your [homepage](https://jydenn.github.io/website/) and your [holiday project page](https://jydenn.github.io/website/XMASProject/navidad.html) that serves no good purpose.  It makes users click twice to get to their destination instead of once.  Please fix that this week.  You could :+1: 

1. Rename navidad.html to index.html and leave the homepage link unchanged.
2. Change the link on your homepage to link directly to navidad.html.

Also, please add a new subsection on your homepage titled something like "What's New", as I requested on our [last week's assignment page](https://ict.gctaa.net/sections/webdesign/goals/week19.html).

**Comment by jydenn** [comment]
Fixed and added what's new
