### ISSUE TITLE
Add working validation links for HTML and CSS to all pages and fix validation errors

### ISSUE THREAD

**Issue by jelkner** [jydenn/website#5]
The CSS validation link on your [homepage](https://jydenn.github.io/website/) needs to be fixed, and there are HTML validation errors on the [K1CKS](https://jydenn.github.io/website/K1CKS/) page.

**Comment by jelkner** [comment]
You're site gets better every time I look at it, but you still need to finish adding the validation links (both HTML and CSS).  I can help you if you need it, but from the looks of your [homepage](https://jydenn.github.io/website/index.html) you're almost there (the CSS validation still needs a fix).

**Comment by jydenn** [comment]
All of them should be fixed now.
